version: 2.1
jobs:
  build:
    docker:
      - image: tsukasaoishi/circleci-ruby:2.6.3
        environment:
          BUNDLE_PATH: .bundle
          RAILS_ENV: production
          NODE_ENV: production

    steps:
      - checkout

      - restore_cache:
          keys:
            - install-gems-201907190019-{{ checksum "Gemfile.lock" }}
            - install-gems-201907190019-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - save_cache:
          paths:
            - .bundle
          key: install-gems-201907190019-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
            - install-yarn-201907190019-{{ checksum "yarn.lock" }}
            - install-yarn-201907190019-

      - run:
          name: assets precompile
          command: |
            bundle exec rails assets:precompile

      - save_cache:
          paths:
            - node_modules
          key: install-yarn-201907190019-{{ checksum "yarn.lock" }}

      - run:
          name: build tar-ball
          command: |
            rm -fr log/* tmp/* node_modules .bundle .git .circleci .rspec
            mkdir -p /tmp/deploy
            tar cvfz /tmp/deploy/${CIRCLE_SHA1}.tgz .

      - run:
          name: upload tar-ball to S3
          command: |
            aws s3 cp /tmp/deploy/${CIRCLE_SHA1}.tgz s3://tsuka-deploy/kaeruspoon/

